### ISSUE TITLE
请问下各位训练这个模型要占多少内存（显存），我设置batch size为4,就用了20多G

### ISSUE THREAD

**Issue by GongCQ** [qingkongzhiqian/GPT2-Summary#13]

**Comment by chenruhai** [comment]
tf_model.h5、merges.txt、special_tokens_map.json、added_tokens.json、tokenizer_config.json

找不到这些文件啊，跑不起来。

报错如下：
`D:\Desktop\pythonProject1_tf\venv\Scripts\python.exe D:/Desktop/pythonProject1_tf/transformers_summarization.py
2021-03-05 23:54:15.018053: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2021-03-05 23:54:15.018378: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "D:/Desktop/pythonProject1_tf/transformers_summarization.py", line 12, in <module>
    tokenizer = GPT2Tokenizer.from_pretrained(model_path)
  File "D:\Desktop\pythonProject1_tf\venv\lib\site-packages\transformers\tokenization_utils_base.py", line 1591, in from_pretrained
    list(cls.vocab_files_names.values()),
OSError: Model name '/pre_train_model/summary_mode/' was not found in tokenizers model name list (gpt2, gpt2-medium, gpt2-large, gpt2-xl, distilgpt2). We assumed '/pre_train_model/summary_mode/' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.json', 'merges.txt'] but couldn't find such vocabulary files at this path or url.

进程已结束,退出代码1
`
